apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deploy
spec:
  selector:
    matchLabels:
      run: jenkins-deploy
  replicas: 1
  template:
    metadata:
      labels:
        run: jenkins-deploy
    spec:
      containers:
      - name: jenkins-deploy
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "2000m"
        volumeMounts:
          - name: jenkins-nfs
            mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-nfs
          nfs:
            server: 192.168.0.2
            path: "/devops/jenkins-nfs"
--- 
kind: Service
apiVersion: v1
metadata:
  name: jenkins-svc
  labels:
    run: jenkins-svc
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    run: jenkins-deploy
  type: NodePort